Log1x/acf-composer

src/Console/stubs/block.full.stub
src/Console/stubs/block.stub

get_field, when it doesn't find a field value, defaults to returning FALSE rather than NULL

Failover on false condition

---

src/Console/stubs/options.full.stub
src/Options.php

This adds the rest of the option page registration options supported by `acf_add_options_page()`

Add the rest of the acf add option page fields

---

composer.json

Since `stoutlogic/acf-builder` requires `"doctrine/inflector":"^1.1"`, we need to make sure there is a compatible version required. #14

Require "doctrine/inflector":"^1.4"

---

src/Console/stubs/block.innerblocks.stub

[From ACF Pro 5.9 RC 1 onward](https://www.advancedcustomfields.com/blog/acf-pro-5-9-rc1/) the key for `<InnerBlocks />` support changed from `__experimental_jsx` to simply `jsx`.

Support key for <InnerBlocks /> changed

---

src/Block.php

As ACF Pro 5.9 introduces support for text / content alignment for blocks (https://github.com/AdvancedCustomFields/acf/issues/335), this adds the needed attributes. Also this adds a check to prevent a bug when set up `align_conten` to use the new matrix control which is available in WordPress 5.5 (https://github.com/AdvancedCustomFields/acf/issues/352)

Add support for 'align_text' and 'align_content'

---

src/Block.php
src/Console/stubs/block.full.stub
src/Console/stubs/block.innerblocks.stub

**Summary**
Add example/preview support as per - https://www.advancedcustomfields.com/resources/acf_register_block_type/
**Preview**
**Example Block - Before**
**Example Block - After**

Add example/previews support

---

src/Block.php

Currently the view file of a Block is based on it's slug. To be able to use own Block Composer for multiple variants, this adds the ability to specify / overwrite the path to the view.

feat: :sparkles: Add ability to override the blocks view (name)

---

src/Concerns/InteractsWithBlade.php

A block with the “preview-“ prefix will be used in the block editor instead of the standard block template if available. My front facing block uses Vue so I wanted to simplify the display in the block editor. Got the idea from block-lab.

Adds editor preview block

---

src/Composer.php

For example : I had a problem with : Repeater -> Accordion -> Flexible Content -> Repeater -> Accordion -> True/False)
Now it's working, every deeper structure will have the default configuration specified in config/acf.php

fix: Default configurations didn't working with deeper structure 

---

src/Block.php

The base class for a block is determined by slugging the block title. For a block with title `Employees` this will result in a base class of `.wp-block-employees` which is fine.
When one localizes the blocks name in the constructor this may lead to unexpected results:
```php
public function __construct(Application $app)
{
parent::__construct($app);
$this->name = __('Employees', 'sage');
$this->slug = 'employees';
}
```
This may translate to a block name of `Mitarbeiter` in German, which will result in a localized base class of `.wp-block-mitarbeiter` so that classes differ when switching languages. 
I propose to use the slug for determining the base class instead.

feat: Use block slug for base class name

---

src/Composer.php

Current condition treats any option that include any of the following words fields, sub_fields, or layouts as a field group.
Therefore, options such as `'acfe_flexible_layouts_thumbnails' => 1,` weren't being passed to the acf-builder properly.
see https://github.com/Log1x/acf-composer/issues/64

Fix treating some options as a layout field

---

src/Console/stubs/block.construct.stub
src/Console/stubs/block.stub

Add undocumented acf anchor support feature - ref: https://support.advancedcustomfields.com/forums/topic/anchor-in-wp-blocks/

Add anchor/id attr support to Block stubs

---

composer.json
composer.lock

Pretty nice fix pushed up to latest version of `StoutLogic/acf-builder` - [Conditionals referencing parent fields](https://github.com/StoutLogic/acf-builder/releases/tag/1.11.0), tested on our latest build and seems to be working well so far.

Bump StoutLogic/acf-builder dependency to v1.11.0

---

src/Block.php

After a dirty PR (#83) this PR adds support to get the active block style based on the CSS classes.
It uses the CSS classes set for the block and matches the patter `is-style-{style}`. If none is found in the class names the method `getStyle()` falls back to the default style defined in the $styles property.
This should make it possible to alter the block / component markup based on the active style.

feat(block): ✨ Add support to get the active block style

---

src/AcfComposer.php

This is a simple modification that will sort the created blocks by name.
In my case, I've been using a custom block category and by default from what I've seen the blocks are ordered by the date, they have been created. Which looks a bit messy on the blocks list.

Sort blocks by name

---

src/Partial.php

This PR prevents the double calls to `$this->fields()` in [Partial](https://github.com/Log1x/acf-composer/blob/master/src/Partial.php).

Prevent double fields() call fixes #111

---

src/AcfComposer.php

Ref: https://github.com/roots/acorn/pull/244

fix: Replace `Str::remove()` with `str_replace()` for Acorn 1.x compatibility

---

src/Block.php

- enhance(block): Conditionally check if example is not null before setting it (Temp Fix for #123)
This can probably be removed once a fix for #123 is implemented in ACF core. This is a very one-off bug. 😦

Check if `example` is null

---

src/Block.php

- chore(block): Change `$example` conditional to explicitly require `false` to disable block preview

Change `$example` conditional

---

src/Composer.php

To make sure that settings on a field overwrite the default settings, the order in which those fields are merged are now reversed. When keys are the same, the second argument in `array_merge()` overwrites the first.

Change the order in which the fields are merged

---

src/Block.php

- enhance(block): Add `$context` param to block render callback (Fixes #130)
- enhance(block): Add `$wp_block` param to block render callback
- enhance(block): Add `$block->context` property to access `$context`
- enhance(block): Add `$block->instance` property to access `$wp_block`
- chore(block): Add missing `$post_id` property definition

Add missing block render callback properties

---

src/Console/stubs/options.full.stub
src/Options.php

There are situations in which it is desirable to register an option
page's fields but omit the page from the admin menu. In these
situations, a developer can set `show_in_menu` to `false`, which
causes the instantiated options object to skip the call it would
otherwise make to `acf_add_options_page`.
This feature does not affect the existing expected functionality of
the plugin, as `show_in_menu` is by default set to `true`.

Add option to toggle option page visibility

---

src/AcfComposer.php
src/Composer.php

I encountered that i cannot use acfs´s `get_field()` within my field declarations. https://github.com/Log1x/acf-composer/issues/162
I noticed that all code is executed immediately and is not registered with the acf/init hook. After changing that it is now possible to use acf related code. This might even fix https://github.com/Log1x/acf-composer/issues/94
I did some test and with these adjustments i was able to create field groups, blocks, options and widgets through the cli. 
The thing I am not sure about is the [registerPlugin](https://github.com/Log1x/acf-composer/blob/146b08dec2723f84ac2c26a3d31dc52934bba8ed/src/AcfComposer.php#LL130C25-L130C25) function. It also registers the path but i didn´t get my head around what this functions does or when it is called. Maybe it needs to be …

Register paths on acf/init

---

src/Block.php
src/Console/stubs/block.stub
src/Console/stubs/views/block.stub

This PR adds native support for the [InnerBlocks `template` property](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/nested-blocks-inner-blocks/#template) making it easy + clean to add block templates to your ACF blocks.
A simple template adding a heading and paragraph would look something like:
```php
public $template = [
'core/heading' => ['placeholder' => 'Hello World'],
'core/paragraph' => ['placeholder' => 'Welcome to the Example block.'],
];
```
I couldn't get block nesting as [pretty as I wanted](https://github.com/Log1x/acf-composer/blob/50af8c2c1f69b7584947ab2ed78cc6c47e1e29b3/src/Block.php#L234-L253) (e.g. when using `core/column` and `core/columns`) but it can be done using the `innerBlocks` attribute.
```php
public $template = [
'core/heading' => …
```

feat(block): Add support for InnerBlocks templates

---

src/Block.php
src/Console/stubs/block.construct.stub
src/Console/stubs/block.stub

Adds the ability to define allowed ancestors rather than direct parents.
https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/nested-blocks-inner-blocks/#child-innerblocks-parent-and-ancestors

enhancement: Add Ancestor allow list to block settings

---

.github/dependabot.yml
.github/workflows/compatibility.yml
.github/workflows/main.yml
composer.lock

Update CI workflow, composer deps and dependabot  

---

src/Block.php
src/Builder.php
src/Builder/FieldBuilder.php
src/Builder/FlexibleContentBuilder.php
src/Builder/GroupBuilder.php
src/Builder/RepeaterBuilder.php
src/Console/UpgradeCommand.php
src/Console/stubs/block.construct.stub
src/Console/stubs/block.stub

- 🧑‍💻 Properly implement context throughout the `Builder` (Fixes #197)
- 🗑️ Deprecate `enqueue()` in place of `assets($block)`
- 🧑‍💻 Update the upgrade command to replace `enqueue()` with `assets($block)`

🧑‍💻 Properly implement context throughout the Builder (Fixes #197)

---

src/Console/stubs/block.construct.stub

Fix for
```
App\Blocks\MyBlock::__construct(): Argument #1 ($app) must be of type Roots\Acorn\Application, Log1x\AcfComposer\AcfComposer given
```

Block Dummyclass expects an AcfComposer object

---

src/Composer.php

This is a fix for issue #205 
It adds `use Exception;` to `Composer.php` to prevent the error `Class "Log1x\AcfComposer\Exception" not found`

fix class Exception not found in Composer.php

---

README.md
src/Block.php
src/Console/UpgradeCommand.php
src/Console/stubs/block.construct.stub
src/Console/stubs/block.stub
src/Console/stubs/field.stub
src/Console/stubs/options.full.stub
src/Console/stubs/options.stub
src/Console/stubs/partial.stub
src/Console/stubs/widget.stub

- ✨ Add an `attributes()` method for cleanly & safely setting block properties instead of construct
- 🧑‍💻 Simplify required arguments for block styles
- 🎨 Improve method typing
- 🧑‍💻 Check for `assets` with `method_exists` to prevent unnecessary clashing
- 🎨 Remove unnecessary `align_content` conditional
- 🎨 Add types to stubs
- 🎨 Improve default typing on the `assets` method (Fixes #206)
- 🎨 Simplify the default `styles` property
- 🎨 Move example data into the `example()` method in the block construct stub
- 🧑‍💻 Update the assets() replacement in acf:upgrade

✨ Add an attributes() method for cleanly & safely setting block properties instead of construct

---

src/Block.php

Hey @Log1x and thanks for updating acf-composer to v3. Massive improvement! 
I just starting to testing it all out on my local and I noticed an memory issue when our Rankmath SEO plugin was generating our sitemap. If the sitemap for example has over 30 URL per page the memory gets exhausted.
I have traced it back to the this line:
https://github.com/Log1x/acf-composer/blob/21f654dbaa6737878661f5b5f24c465cddbd7b67/src/Block.php#L464
I guess with the new caching `$this->template` gets saved on the first built and then carried over to the next time it needs built. If you have a page with a block that are used over 3 times, then it causes a problem. `$this->template` simply gets converted into JSON string everytime. Even if `$this->template` is a string it gets encoded again into JSON. 
On a …

Fixed an issue with getTemplate

---

src/Console/stubs/block.construct.stub

:pencil2: Fix typo in example data

---

src/AcfComposer.php
src/Block.php
src/Console/CacheCommand.php
src/Console/ClearCommand.php
src/Manifest.php
src/Providers/AcfComposerServiceProvider.php

This is a WIP attempt at generating and using `block.json` files when running `acf:cache` for #223 
~~It still needs style/script support but I haven't figured out the best way to pull that off while maintaining some kind of compatibility with `assets()`.~~
Please test using `composer require log1x/acf-composer:dev-feat/json-blocks` and then compile with `acorn acf:cache`.

🚧 Implement block.json generation when caching

---

src/Block.php

Both cached and uncached blocks should use the same ACF block version

---

src/AcfComposer.php

This PR improves compatibility with using option page field values for dynamically creating field groups in fields and blocks. This is done by ensuring that option pages are always loaded & registered prior to composing fields and blocks. 
I also increased the default hook priority to `100` which should improve general compatibility with plugins such as ACF Extended when exploring more advanced functionality.
- 🧑‍💻 Ensure option pages are loaded before fields and blocks
- 🔧 Set the `acf/init` priority to `100` to improve compatibility

🧑‍💻 Improve option page awareness in fields and blocks

---

README.md
src/AcfComposer.php
src/Composer.php
src/Console/stubs/block.construct.stub
src/Console/stubs/block.stub
src/Console/stubs/field.stub
src/Console/stubs/options.full.stub
src/Console/stubs/options.stub
src/Console/stubs/partial.stub
src/Console/stubs/widget.stub
src/Exceptions/DuplicateKeyException.php
src/Exceptions/InvalidFieldsException.php
src/Field.php

- 🧑‍💻 Throw an exception if field group keys are not unique (Fixes #273)
- 🧑‍💻 Throw a `InvalidFieldsException` when fields are invalid
- 🎨 Make generated stub fields variable generic
- 📝 Improve the README examples

🧑‍💻 Throw an exception if field group keys are not unique (Fixes #273)

---

src/Block.php

This lets you set block icons using local SVG assets by prefixing the icon with `asset:` and using dot notation to the path such as:
```php
/**
* The block icon.
*
* @var string|array
*/
public $icon = 'asset:images.blocks.example';
```
would attempt to use `resources/images/blocks/example.svg` as an icon.

✨ Add support for using local SVG assets as block icons (Fixes #265)

---

src/AcfComposer.php

A useless "The render template for this ACF Block was not found" message was added in the `acf_block_render_template` hook when a template file isn't found at some point in ACF Pro 6.3.x.
This hook still makes sense over using a render callback for ACF Composer's use-case despite us echoing the rendered output ourselves so the best workaround is emptying the message using the `acf/blocks/template_not_found_message` filter when a cached block goes to render.

🩹 Suppress the `template_not_found_message` when rendering cached blocks on ACF v6.3.x

---

src/Block.php

🐛 Only set `parent` and `ancestor` when not empty

---

src/Block.php

Fixes #295 
This is a bug fix but could be considered a breaking change.
Scenario that could happen on a site using cached blocks:
- Block was added to a post type that did not support it
- The site is updated to a version of ACF Composer that includes this fix
- The block is still visible on the frontend but will display this message in the editor:
> Your site doesn’t include support for the "acf/block-name" block. You can leave it as-is or remove it.

Nest cached blocks post type restrictions in the block.json acf section

---

src/Block.php

Hi @Log1x,
Happy New Year! 
I have a block registered for which I need to set the `acf_block_version` to `1`. Overwriting the `settings()` method of the class `Block` like this:
```
/**
* Overwrite the block settings to use ACF Block Version 1.
* This prevents the inner blocks from being wrapped into a .acf-innerblocks-container div.
*
* @return Collection The block settings.
*/
public function settings(): Collection
{
return parent::settings()->put('acf_block_version', 1);
}
```
This works perfectly as long as I do not cache the blocks.
This PR adds `blockVersion` & `validate` to the cached `blocks.json` file. Both are settings that might be relevant: https://github.com/AdvancedCustomFields/schemas/blob/7efb0ab78ce903a1414705a83b0fe9b426d5d321/json/block.json#L63
Thanks and kind regards

Adds `blockVersion` & `validate` settings to cached block.json

---

src/AcfComposer.php
src/Block.php
src/Builder.php
src/Composer.php
src/Concerns/HasCollection.php
src/Console/BlockMakeCommand.php
src/Console/CacheCommand.php
src/Console/MakeCommand.php
src/Console/StubPublishCommand.php
src/Console/UpgradeCommand.php
src/Console/UsageCommand.php
src/Widget.php

Add insulation from projects that aren't correctly namespaced that hijack the illuminate collect() function. 
This PR uses the HasCollection trait system used on https://github.com/Log1x/poet/blob/master/src/Concerns/HasCollection.php to insulate the collect() helper function.
Compatibility issue with LearnDash plugin #303

Add HasCollection trait

---

src/Block.php
src/Console/BlockMakeCommand.php
src/Console/stubs/block.stub

This adds proper support for block spacing and improves block attribute consistency when uncached vs cached.
`acf_register_block_type` doesn't support custom attributes for blocks registered using PHP so ACF Composer now has it's own `registerBlockType` method to allow for configuring defaults on things like spacing when not cached as `block.json`.
Ref: #302 #310

✨ Add native support for block spacing

---

src/AcfComposer.php
src/Block.php
src/Console/UpgradeCommand.php
src/Console/stubs/block.localized.stub
src/Console/stubs/block.stub

Refactor `assets()` call to support (a) cached blocks & (b) the iframed Block Editor & Site Editor.
For more detailse see https://github.com/Log1x/acf-composer/issues/304.

Enqueue block assets with 'enqueue_block_assets' action

---

resources/views/alpine-support.blade.php
resources/views/block-editor-filters.blade.php
src/AcfComposer.php
src/Block.php
src/Console/stubs/views/block.stub

- 🩹 Ensure `assets()` receives an array
- 🩹 Fix typography attribute compatibility (Fixes #316)
- ✨ Add view `$attribute` bag support to blocks 
- 💄 Update the block view stub to use the attribute bag
- 🧑‍💻 Improve Alpine support with `@` in blocks while in the editor
- 🧑‍💻 Add the `wp-block-` classname without `acf` namespace to the block list containers

✨ Add view attribute bag support to blocks

---

src/AcfComposer.php
src/Block.php

This improves the [previous solution](https://github.com/Log1x/acf-composer/pull/315) by
- Supporting blocks in synchronised patterns
- Loading assets for blocks on frontend when rendering
This has been tested with cached/uncached blocks in iframed/non-iframed editors.

Improve enqueue block assets with 'enqueue_block_assets' action

---

src/Block.php

Added the ability to manually change the api version of the block, from being hardcoded at 2
```
/**
* The ACF block API version.
*
* @var int
*/
public $apiVersion = 2;
```

Add API versioning to the src/Block

---

src/Builder.php
src/Builder/AccordionBuilder.php
src/Builder/ChoiceFieldBuilder.php
src/Builder/FieldBuilder.php
src/Builder/FlexibleContentBuilder.php
src/Builder/GroupBuilder.php
src/Builder/RepeaterBuilder.php
src/Builder/TabBuilder.php
src/Composer.php
src/Contracts/Composer.php
src/Partial.php

This way you can dynamically set the field name for example.
Examples:
```php
->addPartials([
Example::class => ['test' => 'value'],
Whatever::class,
Another::class => ['another' => 'value'],
])
```
```php
->addPartial(IconSelect::class, [
'field_name' => 'usp_icon',
])
```

Make it possible to pass arguments to partials

---

src/Block.php

Fix block registration compatibility with WordPress 6.8 (v2.1.0)

---

src/Console/StubPublishCommand.php

Running `wp acorn acf:stubs` generates this error:
```
In StubPublishCommand.php line 66:
file_get_contents(/app/web/app/themes/sage/vendor/log1x/acf-composer/src/Console/stubs/block.construct.stub): Failed
to open stream: No such file or directory
```
Replace `block.construct.stub` with `block.localized.stub` in the available stubs array to match the files.

Fix crash when trying to publish stubs using Acorn

---

src/Block.php

https://github.com/Log1x/acf-composer/issues/340#issuecomment-2890124534
Only add `parent` to the settings array if its value is not empty.

Fix block type registration in WordPress 6.8
